name: CD

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Add SSH Key
        run: |
            # Add the SSH private key to a temporary file
            echo "${{ secrets.DIGITAL_OCEAN_SSH }}" > /tmp/ssh_key
            chmod 600 /tmp/ssh_key
            # Start SSH agent and add the key
            eval $(ssh-agent -s)
            ssh-add /tmp/ssh_key
            ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITALOCEAN_IP }} << 'EOF'
            cd time-the-progress

            git pull
            CONTAINER_NAME="time_it_rails"
            docker build -t $CONTAINER_NAME .

            # Check if the container is running
            if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
                echo "Stopping and removing the running container: $CONTAINER_NAME"
                docker stop time_it_rails
                docker rm time_it_rails
                docker run -d -p 3000:3000 -v ./storage:/rails/storage -e RAILS_MASTER_KEY=${{ secrets.MASTER_KEY }} --name time_it_rails time_it_rails
            else
                docker run -d -p 3000:3000 -v ./storage:/rails/storage -e RAILS_MASTER_KEY=${{ secrets.MASTER_KEY }} --name time_it_rails time_it_rails
            fi
            EOF

    