name: CD

on:
  push:
    branches: ['cd']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Add SSH Key
        run: |
            # Add the SSH private key to a temporary file
            echo "${{ secrets.DIGITAL_OCEAN_SSH }}" > /tmp/ssh_key
            chmod 600 /tmp/ssh_key
            # Start SSH agent and add the key
            eval $(ssh-agent -s)
            ssh-add /tmp/ssh_key
            ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITALOCEAN_IP }} << 'EOF'
            cd time-the-progress
            git pull

            # Stop the running container
            docker stop time_it_rails || true
            # Remove old container
            docker rm time_it_rails || true
            # Run a new container from a new image
            docker run -it -p 80:80 -v ./storage:/rails/storage -e RAILS_MASTER_KEY=${{ secrets.MASTER_KEY }} --name time_it_rails time_it_rails
            EOF

    